#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login:
    path: /api/login

login:
    path: /login
    controller: Symfony\Bundle\FrameworkBundle\Controller\AbstractController::render
    defaults:
        template: security/login.html.twig

app_logout:
    path: /logout

registration:
    resource: '../src/Controller/RegisterController.php'
    type: annotation

